Event_Web/Controllers/EventsUserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Event_DAL.Models;
using Microsoft.AspNetCore.Identity;
using Event_BLL.Areas.Identity.Data;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using Event_BLL.Abstract;
using Event_DAL.Repositories.Concrete;

namespace Event_Web.Controllers
{
    public class EventsUserController : BaseController//GenericRepository<Event>
    {
        
        private readonly IEventService _eventService;
        private readonly Kariyer_ProjeContext _context;
        //Event_WebUser event_WebUser;
        public EventsUserController(IEventService eventService, Kariyer_ProjeContext context)
        {
            _eventService = eventService;
            _context = context;
        }

        // GET: Events
        public IActionResult Index()
        {
                    var kariyer_ProjeContext = _context.Events.Where(u => u.UserId==User.FindFirstValue(ClaimTypes.NameIdentifier)).Include(u => u.Category).Include(u => u.City);

            var listAllEmployees =  _eventService.GetAllEventsGeneric().Where(u => u.UserId==User.FindFirstValue(ClaimTypes.NameIdentifier)).Include(u => u.Category).Include(u => u.City);
            return View(listAllEmployees);
            //var kariyer_ProjeContext = _context.Events.Include(u => u.Category).Include(u => u.City);
            //return View(await kariyer_ProjeContext.ToListAsync());
        }

        // GET: Events/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Events == null)
            {
                return NotFound();
            }
            var @event = await _context.Events
                .Include(u => u.Category)
                .Include(u => u.City)
                .FirstOrDefaultAsync(m => m.EventId == id);
            if (@event == null)
            {
                return NotFound();
            }
            return View(@event);
        }
        // GET: Events/Create
        [Authorize(Roles = "User")]
        public IActionResult Create()
        {
            ViewData["CategoryId"] = new SelectList(_context.Categories, "CategoryId", "CategoriyName");
            ViewData["CityId"] = new SelectList(_context.Cities, "CityId", "CityName");
            ViewData["Id"]=User.FindFirstValue(ClaimTypes.NameIdentifier);
            return View();
        }

        [Authorize(Roles = "User")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Event @event)
        {
            if (ModelState.IsValid)
            {
                @event.UserId=User.FindFirstValue(ClaimTypes.NameIdentifier);

                await _eventService.CreateEvent(@event);
                //@event.UserId=User.FindFirstValue(ClaimTypes.NameIdentifier);

                //_context.Add(@event);
                //await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "CategoryId", "CategoriyName", @event.CategoryId);
            ViewData["CityId"] = new SelectList(_context.Cities, "CityId", "CityName", @event.CityId);
            return View(@event);
        }

        // GET: Events/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Events == null)
            {
                return NotFound();
            }

            var @event = await _context.Events.FindAsync(id);
            if (@event == null)
            {
                return NotFound();
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "CategoryId", "CategoryId", @event.CategoryId);
            ViewData["CityId"] = new SelectList(_context.Cities, "CityId", "CityId", @event.CityId);
            return View(@event);
        }

        // POST: Events/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Event @event)
        {
            if (id != @event.EventId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    @event.UserId=User.FindFirstValue(ClaimTypes.NameIdentifier);

                    await _eventService.UpdateEvent(@event);

                    return RedirectToAction(nameof(Index));
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EventExists(@event.EventId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "CategoryId", "CategoryId", @event.CategoryId);
            ViewData["CityId"] = new SelectList(_context.Cities, "CityId", "CityId", @event.CityId);
            return View(@event);
        }

        // GET: Events/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Events == null)
            {
                return NotFound();
            }
            var @event = await _context.Events
                .Include(u => u.Category)
                .Include(u => u.City)
                .FirstOrDefaultAsync(m => m.EventId == id);
            if (@event == null)
            {
                return NotFound();
            }
            return View(@event);
        }

        // POST: Events/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _eventService.DeleteEvent(id);
            return RedirectToAction(nameof(Index));
        }

        private bool EventExists(int id)
        {
            return _context.Events.Any(e => e.EventId == id);
        }
    }

    //    private readonly Kariyer_ProjeContext _context;
    //    //Event_WebUser event_WebUser;
    //    public EventsUserController(Kariyer_ProjeContext context)
    //    {
    //        _context = context;

    //    }

    //    // GET: Events
    //    public async Task<IActionResult> Index()
    //    {
    //        //var kariyer_ProjeContext = _context.Events.Include(u => u.Category).Include(u => u.City);
    //        var kariyer_ProjeContext = _context.Events.Where(u => u.UserId==User.FindFirstValue(ClaimTypes.NameIdentifier)).Include(u => u.Category).Include(u => u.City);
    //        return View(await kariyer_ProjeContext.ToListAsync());
    //    }

    //    // GET: Events/Details/5
    //    public async Task<IActionResult> Details(int? id)
    //    {
    //        if (id == null || _context.Events == null)
    //        {
    //            return NotFound();
    //        }
    //        var @event = await _context.Events
    //            .Include(u => u.Category)
    //            .Include(u => u.City)
    //            .FirstOrDefaultAsync(m => m.EventId == id);
    //        if (@event == null)
    //        {
    //            return NotFound();
    //        }
    //        return View(@event);
    //    }
    //    // GET: Events/Create
    //    [Authorize(Roles = "User")]
    //    public IActionResult Create()
    //    {
    //        ViewData["CategoryId"] = new SelectList(_context.Categories, "CategoryId", "CategoriyName");
    //        ViewData["CityId"] = new SelectList(_context.Cities, "CityId", "CityName");
    //        ViewData["Id"]=User.FindFirstValue(ClaimTypes.NameIdentifier);
    //        return View();
    //    }

    //    [Authorize(Roles = "User")]
    //    [HttpPost]
    //    [ValidateAntiForgeryToken]
    //    public async Task<IActionResult> Create(Event @event)
    //    {
    //        if (ModelState.IsValid)
    //        {
    //            @event.UserId=User.FindFirstValue(ClaimTypes.NameIdentifier);

    //            _context.Add(@event);
    //            await _context.SaveChangesAsync();
    //            return RedirectToAction(nameof(Index));
    //        }
    //        ViewData["CategoryId"] = new SelectList(_context.Categories, "CategoryId", "CategoriyName", @event.CategoryId);
    //        ViewData["CityId"] = new SelectList(_context.Cities, "CityId", "CityName", @event.CityId);
    //        return View(@event);
    //    }
    //    // GET: Events/Edit/5
    //    public async Task<IActionResult> Edit(int? id)
    //    {
    //        if (id == null || _context.Events == null)
    //        {
    //            return NotFound();
    //        }

    //        var @event = await _context.Events.FindAsync(id);
    //        if (@event == null)
    //        {
    //            return NotFound();
    //        }
    //        ViewData["CategoryId"] = new SelectList(_context.Categories, "CategoryId", "CategoryId", @event.CategoryId);
    //        ViewData["CityId"] = new SelectList(_context.Cities, "CityId", "CityId", @event.CityId);
    //        return View(@event);
    //    }

    //    // POST: Events/Edit/5
    //    // To protect from overposting attacks, enable the specific properties you want to bind to.
    //    // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
    //    [HttpPost]
    //    [ValidateAntiForgeryToken]

Event_Web/Controllers/FreeEventsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Event_DAL.Models;
using Microsoft.AspNetCore.Identity;
using Event_BLL.Areas.Identity.Data;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;

namespace Event_Web.Controllers
{
    public class FreeEventsController : BaseController
    {

        private readonly Kariyer_ProjeContext _context;
        //Event_WebUser event_WebUser;
        public FreeEventsController(Kariyer_ProjeContext context)
        {
            _context = context;          
           
        }

        // GET: Events
        public async Task<IActionResult> Index()
        {
            var kariyer_ProjeContext = _context.Events.Include(u => u.Category).Include(u => u.City);
            //var kariyer_ProjeContext = _context.Events.Where(u => u.UserId==User.FindFirstValue(ClaimTypes.NameIdentifier)).Include(u => u.Category).Include(u => u.City);
            return View(await kariyer_ProjeContext.ToListAsync());
        }

        // GET: Events/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Events == null)
            {
                return NotFound();
            }
            var @event = await _context.Events
                .Include(u => u.Category)
                .Include(u => u.City)
                .FirstOrDefaultAsync(m => m.EventId == id);
            if (@event == null)
            {
                return NotFound();
            }
            return View(@event);
        }
        // GET: Events/Create
        [Authorize(Roles = "User")]
        public IActionResult Create()
        {
            ViewData["CategoryId"] = new SelectList(_context.Categories, "CategoryId", "CategoriyName");
            ViewData["CityId"] = new SelectList(_context.Cities, "CityId", "CityName");
            ViewData["Id"]=User.FindFirstValue(ClaimTypes.NameIdentifier);
            return View();
        }
        // POST: Events/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "User")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("EventId,EventName,EventDate,EventLastApplicationDate,EventDescription,CityId,EventAddress,EventQuota,CategoryId")] Event @event)
        {
            if (ModelState.IsValid)
            {
                
                @event.UserId=User.FindFirstValue(ClaimTypes.NameIdentifier);
                
                _context.Add(@event);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "CategoryId", "CategoriyName", @event.CategoryId);
            ViewData["CityId"] = new SelectList(_context.Cities, "CityId", "CityName", @event.CityId);
            return View(@event);
        }

        // GET: Events/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Events == null)
            {
                return NotFound();
            }

            var @event = await _context.Events.FindAsync(id);
            if (@event == null)
            {
                return NotFound();
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "CategoryId", "CategoriyName", @event.CategoryId);
            ViewData["CityId"] = new SelectList(_context.Cities, "CityId", "CityName", @event.CityId);
            return View(@event);
        }

        // POST: Events/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("EventId,EventName,EventDate,EventLastApplicationDate,EventDescription,CityId,EventAddress,EventQuota,CategoryId,UserId")] Event @event)
        {
            if (id != @event.EventId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(@event);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EventExists(@event.EventId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "CategoryId", "CategoriyName", @event.CategoryId);
            ViewData["CityId"] = new SelectList(_context.Cities, "CityId", "CityName", @event.CityId);
            return View(@event);
        }

        // GET: Events/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Events == null)
            {
                return NotFound();
            }

            var @event = await _context.Events
                .Include(u => u.Category)
                .Include(u => u.City)
                .FirstOrDefaultAsync(m => m.EventId == id);
            if (@event == null)
            {
                return NotFound();
            }

            return View(@event);
        }

        // POST: Events/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Events == null)
            {
                return Problem("Entity set 'Kariyer_ProjeContext.Events'  is null.");
            }
            var @event = await _context.Events.FindAsync(id);
            if (@event != null)
            {
                _context.Events.Remove(@event);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EventExists(int id)
        {
          return _context.Events.Any(e => e.EventId == id);
        }
    }
}

Event_Web/Views/FreeEvents/Create.cshtml
@model Event_DAL.Models.Event

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>Event</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="EventName" class="control-label"></label>
                <input asp-for="EventName" class="form-control" />
                <span asp-validation-for="EventName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EventDate" class="control-label"></label>
                <input asp-for="EventDate" class="form-control" />
                <span asp-validation-for="EventDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EventLastApplicationDate" class="control-label"></label>
                <input asp-for="EventLastApplicationDate" class="form-control" />
                <span asp-validation-for="EventLastApplicationDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EventDescription" class="control-label"></label>
                <input asp-for="EventDescription" class="form-control" />
                <span asp-validation-for="EventDescription" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CityId" class="control-label"></label>
                <select asp-for="CityId" class="form-control" asp-items="ViewBag.CityId"></select>
            </div>
            <div class="form-group">
                <label asp-for="EventAddress" class="control-label"></label>
                <input asp-for="EventAddress" class="form-control" />
                <span asp-validation-for="EventAddress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EventQuota" class="control-label"></label>
                <input asp-for="EventQuota" class="form-control" />
                <span asp-validation-for="EventQuota" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CategoryId" class="control-label"></label>
                <select asp-for="CategoryId" class="form-control" asp-items="ViewBag.CategoryId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
    await Html.RenderPartialAsync("_ValidationScriptsPartial");
}
}

Event_Web/Views/FreeEvents/Delete.cshtml
@model Event_DAL.Models.Event

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Event</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EventName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EventName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EventDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EventDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EventLastApplicationDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EventLastApplicationDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EventDescription)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EventDescription)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EventAddress)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EventAddress)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EventQuota)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EventQuota)
        </dd>

       
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Category)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Category.CategoryId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.City)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.City.CityId)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="EventId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Event_Web/Views/FreeEvents/Details.cshtml
@model Event_DAL.Models.Event

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Event</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EventName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EventName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EventDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EventDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EventLastApplicationDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EventLastApplicationDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EventDescription)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EventDescription)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EventAddress)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EventAddress)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EventQuota)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EventQuota)
        </dd>

        
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Category)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Category.CategoryId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.City)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.City.CityId)
        </dd>
         <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TicketFee)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TicketFee)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.EventId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Event_Web/Views/FreeEvents/Edit.cshtml
@model Event_DAL.Models.Event

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>Event</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="EventId" />
            <div class="form-group">
                <label asp-for="EventName" class="control-label"></label>
                <input asp-for="EventName" class="form-control" />
                <span asp-validation-for="EventName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EventDate" class="control-label"></label>
                <input asp-for="EventDate" class="form-control" />
                <span asp-validation-for="EventDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EventLastApplicationDate" class="control-label"></label>
                <input asp-for="EventLastApplicationDate" class="form-control" />
                <span asp-validation-for="EventLastApplicationDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EventDescription" class="control-label"></label>
                <input asp-for="EventDescription" class="form-control" />
                <span asp-validation-for="EventDescription" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CityId" class="control-label"></label>
                <select asp-for="CityId" class="form-control" asp-items="ViewBag.CityId"></select>
                <span asp-validation-for="CityId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EventAddress" class="control-label"></label>
                <input asp-for="EventAddress" class="form-control" />
                <span asp-validation-for="EventAddress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EventQuota" class="control-label"></label>
                <input asp-for="EventQuota" class="form-control" />
                <span asp-validation-for="EventQuota" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CategoryId" class="control-label"></label>
                <select asp-for="CategoryId" class="form-control" asp-items="ViewBag.CategoryId"></select>
                <span asp-validation-for="CategoryId" class="text-danger"></span>
            </div>      
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Event_Web/Views/FreeEvents/Index.cshtml
@model IEnumerable<Event_DAL.Models.Event>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Index      </h1> @Html.ActionLink("Go to my events","Index", "EventsUser", null, null)

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.EventName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EventDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EventLastApplicationDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EventDescription)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EventAddress)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EventQuota)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Category)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.City)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TicketFee)
            </th>

        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            if (item.TicketFee==0)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.EventName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.EventDate)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.EventLastApplicationDate)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.EventDescription)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.EventAddress)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.EventQuota)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Category.CategoriyName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.City.CityName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.TicketFee)
                    </td>
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.EventId">Edit</a> |
                        <a asp-action="Details" asp-route-id="@item.EventId">Details</a> |
                        <a asp-action="Delete" asp-route-id="@item.EventId">Delete</a>
                    </td>
                </tr>
            }

        }
    </tbody>
</table>